version: '1.0.4'
debug: false
data_import:
    input_files: 'auto'
    eddypro_fo:
        repair_time: true
        missing_data_codes: [-9999]
        time_col: 'time'
        try_time_formats: ['%H:%M', '%H:%M:%S']
        date_col: 'date'
        try_date_formats: ['%d.%m.%Y', '%d/%m/%Y', '%Y-%m-%d']
    eddypro_biomet:
        repair_time: true
        missing_data_codes: [-9999]
        datetime_col: 'TIMESTAMP_1'
        try_datetime_formats: ['%Y-%m-%d %H%M', '%d.%m.%Y %H:%M']
    ias:
        repair_time: true
        missing_data_codes: [-9999]
        datetime_col: 'TIMESTAMP_START'
        try_datetime_formats: '%Y%m%d%H%M'
        skip_validation: false
    csf:
        repair_time: true
        missing_data_codes: [-9999, NAN]
        datetime_col: 'TIMESTAMP'
        try_datetime_formats: ['%Y-%m-%d %H:%M:%S', '%d.%m.%Y %H:%M']
        empty_co2_strg: true
    import_mode: 'AUTO'  # EDDYPRO_FO, EDDYPRO_FO_AND_BIOMET, IAS, CSF, CSF_AND_BIOMET, AUTO
    time_col: 'datetime'
data_export:
    ias: {out_fname_ver_suffix: auto, split_intervals: YEAR}
metadata:
    site_name: 'auto'
filters:

calc:
    has_meteo: true
    calc_nee: true
    calc_with_strg: false
reddyproc:
    is_to_apply_u_star_filtering: true
    ustar_threshold_fallback: 0.01
    ustar_rg_source: 'Rg'  # Rg_th_Py, Rg_th_REP, Rg, ""
    is_bootstrap_u_star: false
    u_star_seasoning: 'Continuous'  # WithinYear, Continuous, User
    is_to_apply_partitioning: true
    partitioning_methods: [Reichstein05, Lasslop10]  # Reichstein05, Lasslop10
    latitude: 56.5
    longitude: 32.6
    timezone: 3.0
    temperature_data_variable: 'Tair'
    site_id: ''
    u_star_method: 'RTw'
    is_to_apply_gap_filling: true
    input_file: ''
    output_dir: 'output\reddyproc'
    log_fname_end: '_log.txt'
